# Generated by Django 4.2.7 on 2023-12-09 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=13, verbose_name='Phone Number'),
        ),
    ]
